import { ROLE_VISUAL_ACTIONS, ROLE_VISUAL_EMOTIONS } from "../../shared/role-visual-states.js";
import { STORY_TIME_SEGMENTS, normalizeStoryClock, normalizeStoryEvent } from "../../shared/story-time.js";
import { CORE_AVATAR_PRESETS } from "../config/avatar-presets.js";

/**
 * Creates a fresh Vue state tree for one app instance.
 * Keep defaults neutral: persisted user data is merged during mounted().
 */
export function createAppState() {
  return {
    mobileTab: "chat",
    directApiMode: Boolean(window.__NIGHT_MAILBOX_MOBILE__),
    standaloneMode: Boolean(window.__NIGHT_MAILBOX_STANDALONE__),
    appShellMode: Boolean(window.__NIGHT_MAILBOX_APP_SHELL__),
    motionDisplayEnabled: false,

    onboardingCompleted: false,
    onboardingStep: 1,
    onboardingStepLabels: ["连接", "我的身份", "世界", "人物", "确认"],
    onboardingWorldMode: "ai",
    onboardingWorldTemplateId: "mystery-delivery-lover",
    onboardingRoleTemplateId: "",
    onboardingDismissed: false,
    storyInitialized: false,
    storyInitializing: false,
    worldVersion: 0,
    worldSyncPending: false,
    savedWorldHash: "",

    userProfile: { name: "旅行者", gender: "未指定", pronoun: "TA" },
    profile: {
      name: "", age: 24, gender: "未指定", personality: "", relation: "旅伴",
      prompt: "", appearance: "", imagePrompt: "", avatarUrl: "", worldVersion: 0,
      derivedProfile: {},
    },
    ensemble: {
      enabled: false,
      autoGuests: true,
      maxTurns: 3,
      friend: {
        name: "", age: 24, gender: "未指定", personality: "", relation: "",
        prompt: "", appearance: "", imagePrompt: "", avatarUrl: "",
        derivedProfile: {},
      },
      customRoles: [],
      temporaryRoles: [],
    },
    coreAvatarPresets: CORE_AVATAR_PRESETS,
    avatarUploadingId: "",

    apiMode: "demo",
    chatProvider: "chat",
    chatApiMode: "disabled",
    chatModel: "",
    availableChatModels: [],
    chatModelsLoading: false,
    chatCatalogVerified: false,
    chatConnectionVerified: false,
    chatModelPreferenceLoaded: false,
    modelConnectionWarning: "",
    imageMode: "disabled",
    imageModel: "",
    customImageModel: "",
    availableImageModels: [],
    imageModelsLoading: false,
    imageCatalogVerified: false,
    imageConnectionVerified: false,
    imageConnectionWarning: "",
    imageModelPreferenceLoaded: false,

    settingsOpen: false,
    roleDetailOpen: false,
    roleDetailTargetId: "",
    roleDetailTab: "profile",
    characterPromptOpen: false,
    characterPromptPreparing: false,
    characterPromptFallback: false,
    characterGenerating: false,
    characterPrompt: "",
    characterTargetId: "",
    selectedRoleReferenceImage: null,
    roleReferencePickerOpen: false,
    roleProfileGenerating: false,
    roleProfileGenerationIds: [],
    roleAiInstruction: "",
    aiProposal: null,
    aiProposalView: "after",

    imageEnabled: false,
    imageGenerating: false,
    imagePromptPreparing: false,
    imagePrompt: "",
    imageQuality: "standard",
    imageJobs: [],
    activeImageJobs: [],
    galleryTab: "scene",
    galleryDisplayLimit: 18,
    imagePreviewJob: null,
    imagePreviewSrc: "",
    imagePreviewLoading: false,
    imagePreviewError: "",
    imagePreviewScale: 1,
    imagePreviewOffsetX: 0,
    imagePreviewOffsetY: 0,
    imagePreviewDetailsVisible: false,
    imagePreviewItems: [],
    imagePreviewPointers: {},
    imagePreviewGesture: null,
    imageDeletingId: "",
    imageJobPollTimer: null,
    notifiedImageJobIds: [],
    imageStylePresets: ["2d动漫", "3d动漫", "电影写实", "暗黑奇幻"],
    imageStylePreset: "",
    imageStyleCustom: "",
    characterImageStylePreset: "",
    characterImageStyleCustom: "",

    tokenUsage: null,
    tokenUsageLoading: false,
    tokenPriceInput: "",
    tokenPriceOutput: "",

    visualStateEditorId: "",
    visualBatchSubmitting: false,
    visualStatePreview: null,
    visualEmotionOptions: ROLE_VISUAL_EMOTIONS,
    visualActionOptions: ROLE_VISUAL_ACTIONS,
    backgroundComposerOpen: false,
    backgroundPromptPreparing: false,
    backgroundGenerating: false,
    stageBackground: { prompt: "", imageUrl: "", imageJobId: "" },
    stageSpeaker: "",
    stageRoleId: "",
    stageStateId: "",
    stageEmotion: "neutral",
    stageAction: "idle",
    stageIntensity: 0.45,
    stageMotionNonce: 0,
    stageLayers: [{ url: "" }, { url: "" }],
    stageActiveLayer: 0,
    stageTransitionTimer: null,
    stageSequenceTimers: [],
    preloadedVisualUrls: [],
    portraitPreviewOpen: false,

    worldSetting: "",
    worldSeed: "",
    worldGenerating: false,
    storySummary: "",
    roleMemories: {},
    autoCompress: true,
    autoCompressThreshold: 40,
    autoCompressFailStreak: 0,
    summaryUpdatedAt: "",
    summarySaving: false,
    summarizing: false,
    randomRoleEnabled: true,
    randomRoleInterval: 18,
    nextGuestAt: 18,
    actionStyle: "行动型",

    storyClock: normalizeStoryClock({ day: 1, segment: "morning", location: "" }),
    storyEvents: [],
    storyTimeSegments: STORY_TIME_SEGMENTS,
    timeSheetOpen: false,
    eventEditorOpen: false,
    editingStoryEventId: "",
    eventParticipantText: "",
    eventDraft: normalizeStoryEvent({
      id: "story-event-draft", title: "", day: 1, segment: "morning", status: "confirmed",
    }),
    timeJumpOpen: false,
    timeJumpDays: 1,
    timeJumpSegment: "dawn",
    timeJumpKeepOverdue: true,
    timeJumpAddTransition: true,
    dayCount: 1,

    sending: false,
    draft: "",
    editingMessageId: null,
    editingMessageContent: "",
    messages: [],
    messageDisplayLimit: 40,
    messageDisplayBatch: 30,
    chatRequestId: 0,
    ensemblePlaybackToken: 0,
    ensemblePlaying: false,
    lastReplyStartId: null,
    suggestions: [],
    suggestionsLoading: false,
    suggestionsVisible: false,
    suggestionRequestId: 0,
    suggestionRefreshTimer: null,
    currentSuggestionStyle: "",

    promptSaving: false,
    promptSection: "",
    systemPrompt: "",
    defaultSystemPrompt: "",
    promptVariableHelp: "{{name}}、{{age}}、{{personality}}、{{relation}}",
    settingsReady: false,
    roleAutoSaveTimer: null,
    storyAutoSaveTimer: null,
    settingsSyncTimer: null,

    backupBusy: "",
    backupStatus: "",
    assetStorage: null,
    historyStorage: null,
    memoryStorage: null,
    historyRetentionDays: 90,
    historyListOpen: false,
    pendingBackup: null,
    pendingBackupMeta: null,
    errorLogs: [],
    errorLogFilter: "all",
    globalErrorHandler: null,
    rejectionErrorHandler: null,

    mobileMenuOpen: false,
    toast: "",
    toastTimer: null,
    personalities: [
      { name: "娇小可爱", icon: "♡", copy: "软萌俏皮" },
      { name: "俏皮", icon: "✦", copy: "轻松有趣" },
      { name: "理性", icon: "◇", copy: "清醒可靠" },
      { name: "治愈", icon: "☾", copy: "安静倾听" },
    ],
    tasks: [
      { id: 1, title: "互道一声早安", detail: "完成今天的第一次问候", points: 10, icon: "☀", done: true },
      { id: 2, title: "分享此刻心情", detail: "用一句话告诉她今天怎样", points: 15, icon: "♡", done: false },
      { id: 3, title: "走一段放松的路", detail: "离开屏幕，散步 10 分钟", points: 20, icon: "↝", done: false },
      { id: 4, title: "认真说一句晚安", detail: "用一句话结束今天的故事", points: 25, icon: "☾", done: false },
    ],
  };
}
